### ISSUE TITLE
Key binds problems

### ISSUE THREAD

**Issue by Vinzound** [PaintNinja/SpammyCombat#3]
The key bind settings of other mods are reset when reopening Minecraft with this mod installed :(

I use version 1.20.1

**Comment by PaintNinja** [comment]
This mod doesn't have any code related to keybinds and therefore cannot be the culprit. I wish you luck in finding the problematic mod.

**Comment by Vinzound** [comment]
It's strange, because it stopped happening just when I deactivated this mod, perhaps it has some incompatibility with another mod that I have installed. Sorry for the inconvenience.

**Comment by PaintNinja** [comment]
No worries, thanks anyway for reporting a potential issue :)
